from ._tools import (
    set_verbosity,
    detect_dtype,
    union_lists,
    filter_args,
    pruner_sampling,
    BorutaPyWrapper,
    GreedyBorutaPyWrapper,
    TransformerWrapper,
    PValueFeatureSelector,
)

from ._evaluation import (
    classification_report,
    biserial_scorer,
    pearson_scorer,
    kendall_scorer,
    spearman_scorer,
    mcc_scorer,
    pr_auc_scorer,
    roc_auc_scorer,
    ks_scorer,
    ks_statistic_score,
    brier_scorer,
    resolve_scorer,
    scoring_to_metric_column,
    metric_is_lower_better,
    plot_pr_curve,
    plot_roc_curve,
    plot_ks_statistic,
    plot_confusion_matrix,
)

from ._scalers import (
    instantiate_standard_scaler,
    instantiate_minmax_scaler,
    instantiate_robust_scaler,
    instantiate_identity_function,
    instantiate_scaler,
)

from ._dataset_reducer import (
    reduce_dataset,
    stage1_reduce,
    stage2_refine,
)

from ._calibration import (
    ThresholdedClassifier,
    calibrate_pipeline,
    pick_best_calibration_method,
    find_best_threshold,
    compute_calibration_variants,
    plot_calibration_curve,
)

__all__ = [
    "set_verbosity",
    "detect_dtype",
    "union_lists",
    "filter_args",
    "pruner_sampling",
    "BorutaPyWrapper",
    "GreedyBorutaPyWrapper",
    "TransformerWrapper",
    "PValueFeatureSelector",
    "classification_report",
    "biserial_scorer",
    "pearson_scorer",
    "kendall_scorer",
    "spearman_scorer",
    "mcc_scorer",
    "pr_auc_scorer",
    "roc_auc_scorer",
    "ks_scorer",
    "ks_statistic_score",
    "brier_scorer",
    "resolve_scorer",
    "scoring_to_metric_column",
    "metric_is_lower_better",
    "plot_pr_curve",
    "plot_roc_curve",
    "plot_ks_statistic",
    "plot_confusion_matrix",
    "instantiate_standard_scaler",
    "instantiate_minmax_scaler",
    "instantiate_robust_scaler",
    "instantiate_identity_function",
    "instantiate_scaler",
    "reduce_dataset",
    "stage1_reduce",
    "stage2_refine",
    "ThresholdedClassifier",
    "calibrate_pipeline",
    "pick_best_calibration_method",
    "find_best_threshold",
    "compute_calibration_variants",
    "plot_calibration_curve",
]
